export const ownerNav = [
  { href: "/owner/dashboard", label: "Home", shortLabel: "HOM" },
  { href: "/owner/listing", label: "Listing", shortLabel: "LST" },
  { href: "/owner/plans", label: "Plans", shortLabel: "PLN" },
  { href: "/owner/coupons", label: "Coupons", shortLabel: "CPN" },
  { href: "/owner/admissions", label: "Admissions", shortLabel: "ADM" },
  { href: "/owner/students", label: "Roster", shortLabel: "ROS" },
  { href: "/owner/seats", label: "Seats", shortLabel: "SEA" },
  { href: "/owner/checkins", label: "Attendance", shortLabel: "ATT" },
  { href: "/owner/payments", label: "Payments", shortLabel: "PAY" },
  { href: "/owner/reports", label: "Reports", shortLabel: "RPT" },
  { href: "/owner/expenses", label: "Expenses", shortLabel: "EXP" },
  { href: "/owner/marketing", label: "Marketing", shortLabel: "MKT" },
  { href: "/owner/website", label: "Website", shortLabel: "WEB" },
  { href: "/owner/notifications", label: "Notices", shortLabel: "NTC" },
  { href: "/owner/billing", label: "Billing", shortLabel: "BIL" },
  { href: "/owner/settings", label: "Settings", shortLabel: "SET" },
];

export const studentNav = [
  { href: "/student/dashboard", label: "My Library", shortLabel: "LIB" },
  { href: "/student/join-library", label: "Join Library", shortLabel: "JIN" },
  { href: "/student/seat", label: "Seat", shortLabel: "SEA" },
  { href: "/student/payments", label: "Payments", shortLabel: "PAY" },
  { href: "/student/notifications", label: "Alerts", shortLabel: "ALT" },
  { href: "/student/focus", label: "Study Zone", shortLabel: "STZ" },
  { href: "/student/tools", label: "Study Tools", shortLabel: "TLS" },
  { href: "/student/qr", label: "My QR", shortLabel: "QR" },
  { href: "/student/syllabus", label: "Syllabus", shortLabel: "SYL" },
  { href: "/student/revisions", label: "Revision", shortLabel: "REV" },
  { href: "/student/rewards", label: "Rewards", shortLabel: "RWD" },
  { href: "/student/feed", label: "Feed", shortLabel: "FED" },
  { href: "/student/offers", label: "Offers", shortLabel: "OFF" },
  { href: "/student/focus-mode", label: "Focus Mode", shortLabel: "ZEN" },
  { href: "/student/settings", label: "Settings", shortLabel: "SET" },
];

export const adminNav = [
  { href: "/superadmin/dashboard", label: "Overview", shortLabel: "OVR" },
  { href: "/superadmin/libraries", label: "Libraries", shortLabel: "LIB" },
  { href: "/superadmin/marketplace", label: "Marketplace", shortLabel: "MKT" },
  { href: "/superadmin/data", label: "Data", shortLabel: "DAT" },
  { href: "/superadmin/reviews", label: "Reviews", shortLabel: "REV" },
  { href: "/superadmin/offers", label: "Offers", shortLabel: "OFF" },
  { href: "/superadmin/plans", label: "Plans", shortLabel: "PLN" },
  { href: "/superadmin/payments", label: "Payments", shortLabel: "PAY" },
];
