export const ownerNav = [
  { href: "/owner/dashboard", label: "Home", shortLabel: "HOM", group: "Operate" },
  { href: "/owner/admissions", label: "Admissions", shortLabel: "ADM", group: "Operate" },
  { href: "/owner/students", label: "Roster", shortLabel: "ROS", group: "Operate" },
  { href: "/owner/seats", label: "Seats", shortLabel: "SEA", group: "Operate" },
  { href: "/owner/checkins", label: "Attendance", shortLabel: "ATT", group: "Operate" },
  { href: "/owner/payments", label: "Payments", shortLabel: "PAY", group: "Money" },
  { href: "/owner/plans", label: "Plans", shortLabel: "PLN", group: "Money" },
  { href: "/owner/coupons", label: "Coupons", shortLabel: "CPN", group: "Money" },
  { href: "/owner/expenses", label: "Expenses", shortLabel: "EXP", group: "Money" },
  { href: "/owner/billing", label: "Billing", shortLabel: "BIL", group: "Money" },
  { href: "/owner/listing", label: "Listing", shortLabel: "LST", group: "Growth" },
  { href: "/owner/website", label: "Website", shortLabel: "WEB", group: "Growth" },
  { href: "/owner/marketing", label: "Marketing", shortLabel: "MKT", group: "Growth" },
  { href: "/owner/referrals", label: "Referrals", shortLabel: "REF", group: "Growth" },
  { href: "/owner/notifications", label: "Notices", shortLabel: "NTC", group: "Growth" },
  { href: "/owner/reports", label: "Reports", shortLabel: "RPT", group: "Insights" },
  { href: "/owner/admins", label: "Team", shortLabel: "ADM", group: "Setup" },
  { href: "/owner/settings", label: "Settings", shortLabel: "SET", group: "Setup" },
];

export const studentNav = [
  { href: "/student/dashboard", label: "My Library", shortLabel: "LIB", group: "Library" },
  { href: "/student/seat", label: "Seat", shortLabel: "SEA", group: "Library" },
  { href: "/student/payments", label: "Payments", shortLabel: "PAY", group: "Library" },
  { href: "/student/notifications", label: "Alerts", shortLabel: "ALT", group: "Library" },
  { href: "/student/scanner", label: "Scanner", shortLabel: "QR", group: "Library" },
  { href: "/student/focus", label: "Study Zone", shortLabel: "STZ", group: "Study" },
  { href: "/student/syllabus", label: "Syllabus", shortLabel: "SYL", group: "Study" },
  { href: "/student/planner", label: "Planner", shortLabel: "PLN", group: "Study" },
  { href: "/student/revisions", label: "Revision", shortLabel: "REV", group: "Study" },
  { href: "/student/tools", label: "Study Tools", shortLabel: "TLS", group: "Study" },
  { href: "/student/focus-mode", label: "Focus Mode", shortLabel: "ZEN", group: "Study" },
  { href: "/student/feed", label: "Feed", shortLabel: "FED", group: "Community" },
  { href: "/student/rewards", label: "Rewards", shortLabel: "RWD", group: "Community" },
  { href: "/student/referrals", label: "Referrals", shortLabel: "REF", group: "Community" },
  { href: "/student/offers", label: "Offers", shortLabel: "OFF", group: "Community" },
  { href: "/student/settings", label: "Settings", shortLabel: "SET", group: "Account" },
];

export const adminNav = [
  { href: "/superadmin/dashboard", label: "Overview", shortLabel: "OVR", group: "Control" },
  { href: "/superadmin/libraries", label: "Libraries", shortLabel: "LIB", group: "Control" },
  { href: "/superadmin/plans", label: "Plans", shortLabel: "PLN", group: "Control" },
  { href: "/superadmin/payments", label: "Payments", shortLabel: "PAY", group: "Control" },
  { href: "/superadmin/access", label: "Access", shortLabel: "ACC", group: "Control" },
  { href: "/superadmin/marketplace", label: "Marketplace", shortLabel: "MKT", group: "Content" },
  { href: "/superadmin/blogs", label: "Blogs", shortLabel: "BLG", group: "Content" },
  { href: "/superadmin/syllabus", label: "Syllabus", shortLabel: "SYL", group: "Content" },
  { href: "/superadmin/book-requests", label: "Book Requests", shortLabel: "BKS", group: "Content" },
  { href: "/superadmin/reviews", label: "Reviews", shortLabel: "REV", group: "Content" },
  { href: "/superadmin/offers", label: "Offers", shortLabel: "OFF", group: "Content" },
  { href: "/superadmin/data", label: "Data", shortLabel: "DAT", group: "System" },
  { href: "/superadmin/integrations", label: "Integrations", shortLabel: "INT", group: "System" },
  { href: "/superadmin/referrals", label: "Referrals", shortLabel: "REF", group: "System" },
];
